python -m pytest
@pytest.mark.xfail

Дефекты
Класс StringUtils

1. Функция capitilize (Принимает на вход текст, делает первую букву заглавной и возвращает этот же текст)
Тест №2 (На вход строка только с прописными буквами)
Фактический результат: Оставляет прописной только первую букву, остальные становятся строчными ('GOODBYE' --> 'Goodbye')
Ожидаемый результат: Оставляет прописными все буквы (Предполагаемый вариант, данный случай никак не обознаяен в ТЗ)
Комментарий: уточнить, является ли это багом


2. Функция starts_with (Возвращает `True`, если строка начинается с заданного символа и `False` - если нет)
Тест №56 (НЕГАТИВНЫЙ: несколько начальных символов)

@pytest.mark.xfail
def test_starts_with_several_symbols():
    string_util = StringUtils()
    res = string_util.starts_with('And it sounds just like a song', 'And')
    assert res == True

Фактический результат: True (Указанные символы соответствуют начальным)
Ожидаемый результат: Ошибка (В описании функции речь идет об одном символе, случай с несколькими символами требует уточнения в ТЗ)

3. Функция end_with (Возвращает True, если строка заканчивается заданным символом и False - если нет)
Тест №69 (НЕГАТИВНЫЙ: несколько конечных символов)

@pytest.mark.xfail
def test_end_with_several_symbols():
    string_util = StringUtils()
    res = string_util.end_with("You don't have to say you're mine", "ine")
    assert res == True

Фактический результат: True (Указанные символы соответствуют конечным)
Ожидаемый результат: Ошибка (В описании функции речь идет об одном символе, случай с несколькими символами требует уточнения в ТЗ)



Исходя из того, что в условиях домашнего задания указано, что проверки на "Пустую строку" и "Строку с пробелом" - негативные, в большей части 
функций они должны результировать сообщением об ошибке. (Понятно, что в функции "is_empty" эти проверки являются позитивными)
Практически во всех случаях (кроме "is_empty") функции на "Пустую строку" и "Строку с пробелом" не проходили проверку на негативный результат (ошибку) 
и засчитывались как "passed".
Ввиду всего вышепечисленного, прихожу к выводу, что в тест-кейсах № 5, 6, 14, 15, 23, 24, 34, 35, 45, 46, 58, 59, 71, 72 выявлены баги. (помечены маркером @pytest.mark.xfail)